### PR TITLE
2D lattice in polygon

### LINKED ISSUE #36: Create framework to connect edges together
## Summary

It is possible to join to Edges together, but the orientation of each edge is important and cannot be controlled easily. A new framework of connections, connecting Edges together must be created.

### PR DESCRIPTION
**Pull request by debeshmandal**
## Summary

- We can create Polygons easily
- We can create a 2D (flat - i.e. on z=0 plane) lattice within the polygon (this needs to be migrated)
- We now need to create a `Strand` that spans a path within the lattice.
- To do this we will create the following classes that interact with each other:
  - [x] `lattice.LatticeNode` - contains information about the change of angle
  - [x] `lattice.LatticeEdge` - Analogous with a regular `Edge`
  - [x] `lattice.LatticeRoute` - subclass of `oxdna.Strand`, contains an arrangement of  `LatticeEdge` and `LatticeNode` instances but is an oxDNA `Strand` that can be added to a system. This will be returned by a function within `Polygon` called `Polygon.generate_lattice(*args, **kwargs)`

- Since `Edge` and `LatticeEdge` are very similar and will have similar methods and attributes (but not the same) we will also create a lower-level class called `DNAEdge` which allows us to generate an `oxDNA.Strand` easily (using a method) without having to copy and paste code.
  - [x] `tools.DNAEdge` - abstract class which `Edge` and `LatticeEdge` will inherit from - main task is to have a property called `generate_strand(*args, **kwargs)`

The flow will look like this:

image

closes #36, #34, #33, #18

### CODE REVIEW

**Comment by debeshmandal** [comment]
@shanilpanara when you make updates - merge into the `lattice-dev` branch and don't merge this pull request until everything is finished

**Comment by debeshmandal** [comment]
@shanilpanara let's discuss this tomorrow, because now we have the slightly tricky task of combining what you've done with what I've done. Is it clear what I've done with the `LatticeNode`, `LatticeEdge` and `LatticeRoute` classes?

**Comment by shanilpanara** [comment]
@debeshmandal Sure, lets discuss in detail tomorrow :) I spent a couple hours on Friday morning understanding what you've done with all the Lattice classes, and it all seems to make sense to me, the test files certainly helped understanding how you'd use them. Overall, I think it is a smart and tidy way of going about things!

I think I have an idea of how we can merge the two and I also agree LatticeRoute is the end point. 

The tricky part might be selecting the right crossovers when we advance the programme to choose more than 2 crossovers per row, i.e. 4, 6, 8 etc. it certainly increases the number of configurations we can achieve, possibly by  2^x  or something.

I will look into plotting the original inputted polygon shape on top of the grid later today! 

My plan for the rest of today -> I'm going try implementing the following:
- finding and plotting crossover positions on top of the current lattice
- ensuring every row is "paired" into 2 rows of the same length, so that we can get crossovers occuring within the lattice
- changing the "quantising" of every row from multiples of 32, to instead no. of base pairs corresponding to half turns

**Comment by debeshmandal** [comment]
Okay that's interesting about the number of configurations problems - it would be really useful to have a class (maybe `Lattice`) that has a property that tells us the total number of configurations for a given set of constraints on the design - I will make a separate issue for this later down the line. 

We should close up what we're doing at the moment and ensure it's fully documented and has examples before moving onto this kind of thing though. In our meeting tomorrow, let's draft Release Version 0.2.0 - and figure out what's left to fill in. The `LatticeRoute` class should handle all of the visualisation but storing/auto-generating different `LatticeRoute` instances is not necessarily simple because as you say there could be more configurations than can be stored in memory.

I'm not fully sure I understand all the quantisation that you have done, and (I might be wrong) but I think you've missed a trick with specifying the lattice dimensions, but I'll review the code and we can discuss tomorrow

**Pull request merged**
